/**
 * RelaySync/1 framing layer (transfer-protocol.md §3.2).
 *
 *   +----------------+-------------------+----------------------+
 *   | length: uint32 | msg_type: uint8   | payload              |
 *   | (big-endian,   | (see MsgType)     | CBOR map, or binary  |
 *   |  incl. type)   |                   | for CHUNK_DATA       |
 *   +----------------+-------------------+----------------------+
 *
 * CHUNK_DATA carries a fixed 36-byte binary header followed by raw bytes,
 * so hot-path data is zero-copy and never CBOR-wrapped:
 *
 *   file_id_hash : 16 bytes (BLAKE2s-128 of the file id)
 *   offset       : uint64 BE
 *   data_length  : uint32 BE
 *   xxh64        : uint64 BE (seed 0, over the raw bytes)
 *   data         : data_length bytes
 *
 * Golden vectors: tests/vectors/frames.json (generated by scripts/gen-vectors.ts).
 */
import { encode as cborEncode, decode as cborDecode } from "cbor-x";
import { FILE_ID_HASH_BYTES, MAX_FRAME_SIZE, MsgType, type MsgTypeCode } from "./constants.js";

const CHUNK_HEADER_BYTES = FILE_ID_HASH_BYTES + 8 + 4 + 8; // 36

/** Encode a CBOR control frame. */
export function encodeFrame(type: MsgTypeCode, payload: Record<string, unknown>): Buffer {
  const body = Buffer.from(cborEncode(payload));
  const frame = Buffer.alloc(4 + 1 + body.length);
  frame.writeUInt32BE(1 + body.length, 0);
  frame.writeUInt8(type, 4);
  body.copy(frame, 5);
  return frame;
}

/** Encode one CHUNK_DATA frame: binary header + raw chunk bytes. */
export function encodeChunkFrame(opts: {
  fileIdHash: Buffer;
  offset: number;
  data: Buffer;
  xxh64: bigint;
}): Buffer {
  const { fileIdHash, offset, data, xxh64 } = opts;
  if (fileIdHash.length !== FILE_ID_HASH_BYTES) throw new Error("fileIdHash must be 16 bytes");
  const frame = Buffer.alloc(4 + 1 + CHUNK_HEADER_BYTES + data.length);
  frame.writeUInt32BE(1 + CHUNK_HEADER_BYTES + data.length, 0);
  frame.writeUInt8(MsgType.CHUNK_DATA, 4);
  fileIdHash.copy(frame, 5);
  frame.writeBigUInt64BE(BigInt(offset), 5 + FILE_ID_HASH_BYTES);
  frame.writeUInt32BE(data.length, 5 + FILE_ID_HASH_BYTES + 8);
  frame.writeBigUInt64BE(xxh64, 5 + FILE_ID_HASH_BYTES + 12);
  data.copy(frame, 5 + CHUNK_HEADER_BYTES);
  return frame;
}

export interface DecodedChunk {
  type: typeof MsgType.CHUNK_DATA;
  fileIdHash: Buffer;
  offset: number;
  data: Buffer;
  xxh64: bigint;
}

export interface DecodedMessage {
  type: Exclude<MsgTypeCode, typeof MsgType.CHUNK_DATA>;
  payload: Record<string, unknown>;
}

export type DecodedFrame = DecodedChunk | DecodedMessage;

/**
 * Incremental frame decoder. Feed arbitrary TCP segments; complete frames
 * come out. Throws on frames exceeding MAX_FRAME_SIZE.
 */
export class FrameDecoder {
  private buf: Buffer = Buffer.alloc(0);

  feed(segment: Buffer): DecodedFrame[] {
    this.buf = this.buf.length === 0 ? segment : Buffer.concat([this.buf, segment]);
    const out: DecodedFrame[] = [];

    for (;;) {
      if (this.buf.length < 4) break;
      const length = this.buf.readUInt32BE(0);
      if (length < 1 || length > MAX_FRAME_SIZE) {
        throw new Error(`PROTOCOL_VIOLATION: bad frame length ${length}`);
      }
      const total = 4 + length;
      if (this.buf.length < total) break;

      const type = this.buf.readUInt8(4) as MsgTypeCode;
      const payload = this.buf.subarray(5, total);

      if (type === MsgType.CHUNK_DATA) {
        if (payload.length < CHUNK_HEADER_BYTES) {
          throw new Error("PROTOCOL_VIOLATION: short CHUNK_DATA header");
        }
        const fileIdHash = Buffer.from(payload.subarray(0, FILE_ID_HASH_BYTES));
        const offset = Number(payload.readBigUInt64BE(FILE_ID_HASH_BYTES));
        const dataLength = payload.readUInt32BE(FILE_ID_HASH_BYTES + 8);
        const xxh64 = payload.readBigUInt64BE(FILE_ID_HASH_BYTES + 12);
        const dataStart = CHUNK_HEADER_BYTES;
        if (payload.length !== dataStart + dataLength) {
          throw new Error("PROTOCOL_VIOLATION: CHUNK_DATA length mismatch");
        }
        // Copy: `payload` is a view into the shared buffer.
        out.push({ type, fileIdHash, offset, data: Buffer.from(payload.subarray(dataStart)), xxh64 });
      } else {
        const decoded = cborDecode(payload) as Record<string, unknown>;
        out.push({ type: type as DecodedMessage["type"], payload: decoded });
      }

      this.buf = this.buf.subarray(total);
    }
    return out;
  }

  get bufferedBytes(): number {
    return this.buf.length;
  }
}
